security:
#    # ...
#
    providers:
        jsonRpcProvider:
            id: JsonRpcAuthorizationBundle\Service\DefaultUserProviderService
        authorizationProvider:
            id: App\Security\UserProvider
#
    firewalls:
        jsonRpc:
            pattern: ^/jsonRpc
            provider: jsonRpcProvider
            guard:
                authenticators:
                    - JsonRpcAuthorizationBundle\Service\AuthenticationService
        main:
            pattern: ^/
            provider: authorizationProvider
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

#            form_login:
#                login_path: app_login
            logout:
                path:   app_logout

    access_control:
        - { path: '^/jsonRpc', roles: ROLE_RPC_USER }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: ROLE_USER }
