version: "3.3"

services:
    authorization-module:
        hostname: authorization-module
        container_name: authorization-module
        image: docker.pkg.github.com/neznajki/docker-php73/apache:latest
        volumes:
            - .:/www/default:cached
            - $HOME/.bashrc:$HOME/.bashrc:cached
            - $HOME/.profile:$HOME/.profile:cached
            - $HOME/.composer:$HOME/.composer:cached
            - $HOME/.cache/:$HOME/.cache:cached
            - /opt/phpstorm-coverage/:/opt/phpstorm-coverage/:cached
            - /tmp/upload:/tmp/upload:cached
        ports:
            - 80
        dns:
            - 8.8.8.8
            - 10.252.252.252
        links:
            - mysql
        environment:
            - VIRTUAL_HOST=authorization-module.local
            - HTTPS_METHOD=noredirect
            - APACHE_DOCUMENT_ROOT=/www/default/public/

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            VIRTUAL_HOST: 'mysql.authorization-module.local'
            MYSQL_DATABASE: 'authorization'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: '1'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'p1assword'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - /tmp/authorization-module/db:/var/lib/mysql

networks:
    default:
        external:
            name: local_network
